In [3]:
import pandas as pd

# Corpus 

positive = ['This is an excellent movie',
             'The move was fantastic I like it',
             'You should watch it is brilliant',
             'Exceptionally good','Wonderfully directed and executed I like it',
             'Its a fantastic series',
             'Never watched such a brillent movie','It is a Wonderful movie']

negative = ["horrible acting",
            'waste of money',
            'pathetic picture',
            'It was very boring',
            'I did not like the movie',
            'The movie was horrible',
            'I will not recommend',
            'The acting is pathetic']

In [4]:
reviews = [(pr,"positive") for pr in positive] + [(nr,"negative") for nr in negative]

data = pd.DataFrame(reviews,columns=["comment",'review'])

data.head(3)

comment    review
0        This is an excellent movie  positive
1  The move was fantastic I like it  positive
2  You should watch it is brilliant  positive

In [5]:
# shuffle the DataFrame rows
data = data.sample(frac = 1)

In [6]:
from sklearn.preprocessing import LabelEncoder
lb_make = LabelEncoder()
data['review'] = lb_make.fit_transform(data["review"])

data.head()

comment  review
11                           It was very boring       0
15                       The acting is pathetic       0
12                     I did not like the movie       0
2              You should watch it is brilliant       1
4   Wonderfully directed and executed I like it       1

In [7]:
# lower the text
data['comment'] = data['comment'].str.lower()

In [8]:
# find max_length sequence

max_seq_len = max([len([y for y in x.split()]) for x in data['comment']])
max_seq_len

7

In [9]:
# number of samples = 

num_samples = data.shape[0]
num_samples

16

In [11]:
from tensorflow.keras.preprocessing import text

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(data['comment'])
word2id = tokenizer.word_index

word2id['PAD'] = 0
id2word = {v:k for k, v in word2id.items()}
wids = [[word2id[w] for w in text.text_to_word_sequence(doc)] for doc in data['comment']]

In [12]:
vocab_size = len(id2word)

vocab_size

44

In [13]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_inputs = pad_sequences(wids,padding='post')

padded_inputs

array([[ 1,  6, 14, 15,  0,  0,  0],
       [ 3,  9,  4, 10,  0,  0,  0],
       [ 5, 16, 11,  7,  3,  2,  0],
       [17, 18, 19,  1,  4, 20,  0],
       [21, 22, 23, 24,  5,  7,  1],
       [10, 25,  0,  0,  0,  0,  0],
       [ 1,  4,  8, 26,  2,  0,  0],
       [27, 28, 29,  0,  0,  0,  0],
       [ 3, 30,  6, 12,  5,  7,  1],
       [ 5, 31, 11, 32,  0,  0,  0],
       [13,  9,  0,  0,  0,  0,  0],
       [33, 34,  0,  0,  0,  0,  0],
       [35, 36, 37,  8, 38,  2,  0],
       [39,  4, 40, 41,  2,  0,  0],
       [ 3,  2,  6, 13,  0,  0,  0],
       [42,  8, 12, 43,  0,  0,  0]])

In [14]:
sentiments = data['review'].values # output labels

sentiments

array([0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1])

In [16]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(12, input_dim=7, activation='relu')) 
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit the keras model on the dataset
#model.fit(pad_sequences, sentiments, epochs=150, batch_size=10)

In [17]:
sentiments.shape

(16,)

In [19]:
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

import pandas as pd

# load the dataset
dataset = pd.read_csv("diabetes.csv")

dataset.head()

X = dataset.iloc[:,:-1] # 8 Features
y = dataset['Outcome']


# define the keras model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
# fit the keras model on the dataset
model.fit(X, y, epochs=150, batch_size=10)
# evaluate the keras model
_, accuracy = model.evaluate(X, y)
print('Accuracy: %.2f' % (accuracy*100))

Epoch 1/150
77/77 [==============================] - 1s 1ms/step - loss: 2.5637 - accuracy: 0.4284
Epoch 2/150
77/77 [==============================] - 0s 2ms/step - loss: 0.8848 - accuracy: 0.6081
Epoch 3/150
77/77 [==============================] - 0s 2ms/step - loss: 0.7647 - accuracy: 0.6380
Epoch 4/150
77/77 [==============================] - 0s 1ms/step - loss: 0.7180 - accuracy: 0.6341
Epoch 5/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6972 - accuracy: 0.6576
Epoch 6/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6566 - accuracy: 0.6380
Epoch 7/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6363 - accuracy: 0.6289
Epoch 8/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6280 - accuracy: 0.6484
Epoch 9/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6168 - accuracy: 0.6589
Epoch 10/150
77/77 [==============================] - 0s 2ms/step - loss: 0.6157 - accuracy: 0.6589
Epoch 11/

77/77 [==============================] - 0s 1ms/step - loss: 0.5270 - accuracy: 0.7461
Epoch 84/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5200 - accuracy: 0.7513
Epoch 85/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5289 - accuracy: 0.7487
Epoch 86/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5254 - accuracy: 0.7292
Epoch 87/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5346 - accuracy: 0.7435
Epoch 88/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5214 - accuracy: 0.7474
Epoch 89/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5264 - accuracy: 0.7487
Epoch 90/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5169 - accuracy: 0.7565
Epoch 91/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5221 - accuracy: 0.7513
Epoch 92/150
77/77 [==============================] - 0s 1ms/step - loss: 0.5160 - accuracy: 0.7500
Epoch 93/150


In [65]:
padded_inputs.shape

(16, 7)

In [67]:
# define the keras model
model = Sequential()
model.add(Dense(12, input_dim=7, activation='relu')) # 7 Features
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# fit the keras model on the dataset
model.fit(padded_inputs, sentiments, epochs=150, batch_size=10)
# evaluate the keras model

Epoch 1/150
16/16 [==============================] - 0s 18ms/step - loss: 1.7983 - accuracy: 0.5625
Epoch 2/150
16/16 [==============================] - 0s 352us/step - loss: 1.7232 - accuracy: 0.5625
Epoch 3/150
16/16 [==============================] - 0s 418us/step - loss: 1.6363 - accuracy: 0.5625
Epoch 4/150
16/16 [==============================] - 0s 262us/step - loss: 1.5509 - accuracy: 0.5625
Epoch 5/150
16/16 [==============================] - 0s 232us/step - loss: 1.4639 - accuracy: 0.5625
Epoch 6/150
16/16 [==============================] - 0s 222us/step - loss: 1.4019 - accuracy: 0.5625
Epoch 7/150
16/16 [==============================] - 0s 334us/step - loss: 1.3422 - accuracy: 0.6250
Epoch 8/150
16/16 [==============================] - 0s 357us/step - loss: 1.2663 - accuracy: 0.6875
Epoch 9/150
16/16 [==============================] - 0s 285us/step - loss: 1.2171 - accuracy: 0.6875
Epoch 10/150
16/16 [==============================] - 0s 410us/step - loss: 1.1333 - accurac

In [20]:
padded_inputs

array([[ 1,  6, 14, 15,  0,  0,  0],
       [ 3,  9,  4, 10,  0,  0,  0],
       [ 5, 16, 11,  7,  3,  2,  0],
       [17, 18, 19,  1,  4, 20,  0],
       [21, 22, 23, 24,  5,  7,  1],
       [10, 25,  0,  0,  0,  0,  0],
       [ 1,  4,  8, 26,  2,  0,  0],
       [27, 28, 29,  0,  0,  0,  0],
       [ 3, 30,  6, 12,  5,  7,  1],
       [ 5, 31, 11, 32,  0,  0,  0],
       [13,  9,  0,  0,  0,  0,  0],
       [33, 34,  0,  0,  0,  0,  0],
       [35, 36, 37,  8, 38,  2,  0],
       [39,  4, 40, 41,  2,  0,  0],
       [ 3,  2,  6, 13,  0,  0,  0],
       [42,  8, 12, 43,  0,  0,  0]])

In [ ]:
import numpy as np

input = np.array([[ 1,  6, 14, 15,  0,  0,  0]]).reshape(1,7)


model.predict(input)